name: Auto Checkin Job

on:
  schedule:
    # 每天早上 7:00 北京时间（UTC+8）运行
    - cron: "0 23 * * *" # UTC 时间 23:00 对应北京时间 07:00
  workflow_dispatch: # 允许手动触发

jobs:
  auto-sign:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # 指定 Python 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 如果有依赖文件

      # 4. 运行脚本并捕获输出
      - name: Run auto checkin script
        id: run_script # 给步骤命名，方便后续引用输出
        continue-on-error: true
        env:
          COOKIE: ${{ secrets.COOKIE }}
          WECHAT_WEBHOOK_URL: ${{ secrets.WECHAT_WEBHOOK_URL }}
        run: |
          python main_mulit.py
